const REQUIRED_CONFIGURATION = [
  'MONGO_CONNECTION_STRING',
  'CORS_ALLOW_ONLY_PURPULY_ENDPOINTS',
  'STRIPE_VENDOR_PRO_PRICE_ID',
  'STRIPE_SECRET_KEY',
  'STRIPE_SUCCESS_URL',
  'STRIPE_CANCEL_URL',
  'STRIPE_WEBHOOK_SECRET',
  'AWS_S3_BUCKET_NAME',
  'AWS_S3_REGION',
  'AWS_S3_ACCESS_KEY_ID',
  'AWS_S3_ACCESS_KEY_SECRET',
];

const PURPULY_ONLY_ENDPOINTS_REGEX =
  '^(https?://(?:.+.)?purpuly.com(?::d{1,5})?)$';

const FALLBACK_PORT = 8080;

const APPLICATION_LISTENING_PORT = process.env.PORT || FALLBACK_PORT;

export {
  REQUIRED_CONFIGURATION,
  PURPULY_ONLY_ENDPOINTS_REGEX,
  APPLICATION_LISTENING_PORT,
};
